apiVersion: v2
name: woocommerce-store
description: A Helm chart for WooCommerce Store with MySQL
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: wordpress
    version: 15.2.5
    repository: https://charts.bitnami.com/bitnami
    condition: wordpress.enabled
